language: python
python:
  - "2.7"
env:
  - DJANGO=1.4 DB=postgres
  - DJANGO=1.5 DB=postgres
  - DJANGO=1.6 DB=postgres
before_script:
  - mysql -e 'create database django;'
  - psql -c 'create database django;' -U postgres
install:
  - if [[ $DB == mysql ]]; then pip install mysql-python --use-mirrors; fi
  - if [[ $DB == postgres ]]; then pip install psycopg2 --use-mirrors; fi
  - DJANGO_VER=$(./travis_django_version.py $DJANGO)
  - pip install $DJANGO_VER --use-mirrors
  - pip install simplejson --use-mirrors
  - pip install factory_boy --use-mirrors
  - pip install coveralls --use-mirrors
  - pip install . --use-mirrors
script:
  - django-admin.py --version
  - coverage run --source=vkontakte_groups_migration quicktest.py vkontakte_groups_migration
after_success:
  - coveralls
notifications:
  email:
    recipients:
      - ramusus@gmail.com
    on_success: change
    on_failure: change